sript that runs python file

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -2,14 +2,14 @@
 
 # Check if the PYFILE environment variable is set
 if [ -z "$PYFILE" ]; then
-  echo "PYFILE environment variable is not set."
-  exit 1
+	echo "PYFILE environment variable is not set."
+	exit 1
 fi
 
 # Check if the Python script exists
 if [ ! -f "$PYFILE" ]; then
-  echo "Python script '$PYFILE' not found."
-  exit 1
+	echo "Python script '$PYFILE' not found."
+	exit 1
 fi
 
 # Run the Python script
